[2025-03-05T07:35:43.164+0000] {processor.py:186} INFO - Started process (PID=1957) to work on /opt/airflow/dags/etl.py
[2025-03-05T07:35:43.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2025-03-05T07:35:43.165+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:35:43.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2025-03-05T07:35:43.213+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:35:43.212+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:35:43.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2025-03-05T07:35:43.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl.py took 0.062 seconds
[2025-03-05T07:36:13.610+0000] {processor.py:186} INFO - Started process (PID=2021) to work on /opt/airflow/dags/etl.py
[2025-03-05T07:36:13.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2025-03-05T07:36:13.612+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:36:13.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2025-03-05T07:36:13.675+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:36:13.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:36:13.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2025-03-05T07:36:13.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl.py took 0.082 seconds
[2025-03-05T07:36:44.054+0000] {processor.py:186} INFO - Started process (PID=2085) to work on /opt/airflow/dags/etl.py
[2025-03-05T07:36:44.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2025-03-05T07:36:44.057+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:36:44.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2025-03-05T07:36:44.118+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:36:44.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:36:44.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2025-03-05T07:36:44.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl.py took 0.081 seconds
[2025-03-05T07:37:14.594+0000] {processor.py:186} INFO - Started process (PID=2149) to work on /opt/airflow/dags/etl.py
[2025-03-05T07:37:14.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2025-03-05T07:37:14.601+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:37:14.600+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2025-03-05T07:37:14.690+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:37:14.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:37:14.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2025-03-05T07:37:14.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl.py took 0.122 seconds
